config/routes.rb
Rails.application.routes.draw do
  resources :decks, only: %w(index show)
  resources :games, only: %w(new create edit update)

  root to: 'games#new'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck

  def deal_damage(card)
    card.health -= attack
  end

  def dead?
    health <= 0
  end
end

app/models/dead_card.rb
class DeadCard
  include ActiveModel::Model
  def id
    nil
  end

  def name
    'Dead Card'
  end

  def card_type
    'Dead'
  end

  def cost
    0
  end

  def description
    'This card died'
  end

  def flavor
    'Deathly'
  end

  def attack
    0
  end

  def health=(val)
    0
  end

  def health
    0
  end

  def deck
    Deck.new(name: 'Dead Deck')
  end

  def deck_id
    nil
  end

  def dead?
    true
  end

  def deal_damage(card)
    card.health
  end

  def to_partial_path
    'cards/card'
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards, dependent: :destroy
end

app/models/game.rb
class Game
  include ActiveModel::Model
  attr_accessor :player_1, :player_2, :id

  validates_presence_of :player_1, :player_2

  delegate :start, :finish, :finished?, to: :round, prefix: true

  def initialize(attributes = {})
    super(attributes)
    self.round = new_round
  end

  def winner
    return nil unless finished?
    all_players.find(&:has_cards?).try(:name) || :draw
  end

  def finished?
    not(all_players.all?(&:has_cards?))
  end

  private


  attr_accessor :round

  def all_players
    Set.new([player_1, player_2])
  end

  def new_round
    Round.new(player_1: player_1, player_2: player_2)
  end
end

app/models/player.rb
class Player
  include ActiveModel::Model
  attr_accessor :name, :available_cards, :played_card, :next_card_id

  validates_presence_of :name, :available_cards

  def initialize(attributes = {})
    @played_card = attributes.fetch(:played_card) { DeadCard.new }
    super(attributes)
  end

  def play_card
    return played_card unless has_cards?
    return played_card unless played_card.dead?
    @played_card = next_card
    @available_cards = available_cards.where.not(id: @played_card.id)
  end

  def deal_damage(opponent)
    played_card.deal_damage(opponent.played_card)
  end

  def has_cards?
    available_cards.any? || not(played_card.dead?)
  end

  def next_card
    available_cards.find_by(id: next_card_id) || available_cards.first
  end

  def next_card_id
    @next_card_id.to_i
  end
end

app/models/round.rb
class Round
  include ActiveModel::Model
  attr_accessor :player_1, :player_2

  validates_presence_of :player_1, :player_2

  def initialize(attributes = {})
    super
    self.finished = attributes.fetch(:finished) { true }
  end

  def start
    return false unless finished?
    all_players.each(&:play_card)
    self.finished = false
  end

  def finish
    return true if finished?
    player_1.deal_damage(player_2)
    player_2.deal_damage(player_1)
    self.finished = true
  end

  def finished?
    finished
  end

  private

  attr_accessor :finished

  def all_players
    Set.new([player_1, player_2])
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  respond_to :json

  def index
    @decks = Deck.includes(:cards).all
    respond_with @decks, include: :cards
  end

  def show
    @deck = Deck.find(params[:id])
    respond_with @deck, include: :cards
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
    available_cards = Card.all.sample(10)
    @game.player_1 = Player.new(
      available_cards: available_cards,
      played_card: DeadCard.new,
      next_card_id: available_cards.first.id
    )

    available_cards = Card.all.sample(10)
    @game.player_2 = Player.new(
      name: 'Nexus Computer',
      available_cards: available_cards,
      played_card: DeadCard.new,
      next_card_id: available_cards.first.id
    )
  end

  def create
    load_world
    render :edit
  end

  def update
    load_world
    @game.round_start
    @game.round_finish

    if @game.winner
      if @game.winner == :draw
        flash[:notice] = 'It was a draw!'
      else
        flash[:notice] = "#{@game.winner} won!"
      end
      redirect_to new_game_path
    else
      render :edit
    end
  end

  private

  def load_world
    @player_1 = Player.new(player_1_params)
    @player_2 = Player.new(player_2_params)
    @game = Game.new(player_1: @player_1, player_2: @player_2, id: :current)
  end

  def game_params
    params.require(:game)
  end

  def player_1_params
    game_params.require(:player_1).permit(
      %i(
        name
        available_cards
        next_card_id
      )
    ).merge(
      played_card: played_card(game_params[:player_1][:played_card]),
      available_cards: available_cards(game_params[:player_1][:available_cards])
    )
  end

  def player_2_params
    game_params.require(:player_2).permit(
      %i(
        name
        available_cards
        next_card_id
      )
    ).merge(
      played_card: played_card(game_params[:player_2][:played_card]),
      available_cards: available_cards(game_params[:player_2][:available_cards])
    )
  end

  def played_card(param)
    parsed = JSON.parse(param)
    if parsed.present?
      Card.new(parsed)
    else
      DeadCard.new
    end
  end

  def available_cards(param)
    Card.where(id: param.split(','))
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.haml
- form ||= false
.panel.panel-primary
  %h3.panel-heading= card.name
  .panel-body
    %h4!= card.flavor
  .panel-footer
    - if form
      this
      = form.radio_button :next_card_id, card.id
    .to_left.btn.btn-danger Attack (#{card.attack})
    .to_right.btn.btn-success Health (#{card.health})

app/views/games/_form.html.haml
= simple_form_for(@game) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/games/edit.html.haml
.container
  .row
    .col-xs-5
      %h2= @game.player_1.name
      = render @game.player_1.played_card, as: :card
    .col-xs-2.vs_block vs
    .col-xs-5
      %h2= @game.player_2.name
      = render @game.player_2.played_card, as: :card

  .row
    = simple_form_for(@game, method: :put, url: game_path(@game.id)) do |f|
      = f.error_notification

      = f.simple_fields_for :player_1 do |g|
        .form-inputs
          = g.input :name, label: 'your name', as: :hidden,
            input_html: { value: @game.player_1.name }
          .hide= g.input :available_cards,
            input_html: { value: @game.player_1.available_cards.map(&:id).join(',') }
          = g.input :played_card,
            as: :hidden,
            input_html: { value: @game.player_1.played_card.to_json }

          - if @game.player_1.played_card.dead?
            .col-xs-12
              %h3 choose your card to play

            - @game.player_1.available_cards.each do |card|
              .col-xs-3
                = render partial: card, locals: { form: g, card: card }
          - else
            %p nice! Your card is still alive!

      = f.simple_fields_for :player_2 do |g|
        .form-inputs
          = g.input :name, as: :hidden,
            input_html: { value: @game.player_2.name }
          = g.input :available_cards, as: :hidden,
            input_html: { value: @game.player_2.available_cards.map(&:id).join(',') }
          = g.input :played_card, as: :hidden,
            input_html: { value: @game.player_2.played_card.to_json }
          = g.input :next_card_id, as: :hidden,
            input_html: { value: @game.player_2.next_card_id }

      .form-actions.form-actions--full
        = f.button :submit, 'Play Card', class: %w(btn btn-lg btn-success)

  .row= link_to 'Back', games_path

app/views/games/new.html.haml
%h1 New game

= simple_form_for(@game) do |f|
  = f.error_notification

  = f.simple_fields_for :player_1 do |g|
    .form-inputs
      = g.input :name, label: 'your name'
      .hide= g.input 'available_cards',
        input_html: { value: @game.player_1.available_cards.map(&:id).join(',') }
      .hide= g.input :played_card,
        input_html: { value: @game.player_1.played_card.as_json }

  = f.simple_fields_for :player_2 do |g|
    .form-inputs
      = g.input :name, as: :hidden,
        input_html: { value: @game.player_2.name }
      .hide= g.input 'available_cards',
        input_html: { value: @game.player_2.available_cards.map(&:id).join(',') }
      .hide= g.input :played_card,
        input_html: { value: @game.player_2.played_card.as_json }

  .form-actions
    = f.button :submit

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Hearthstone War'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Hearthstone War'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.erb
<h3>Welcome</h3>